More tooling
oparisblue/pipeline pull request #8
Opened 2023-11-28 11:32 UTC by MrSimmmons

hehe yeah...

Happy to modify the prettier config to whatever. I basically just copied the one I use for most of my projects as a baseline.

Have also remove the build dir from the repo since it gets built form scratch in the dockerfile anyway

2023-11-28 23:47 UTC, oparisblue requested changes

2023-11-28 23:47 UTC, oparisblue commented on .prettierrc.json
> +  "useTabs": false
`semi`, `tabWidth` and `useTabs` are all set to their defaults so can be removed

Hot take: `singleQuote` should be `false` (which is the default so removed), and `trailingComma` should be `none`

2023-11-28 23:50 UTC, oparisblue commented
Thanks for fixing this up btw! I think I might need to take another crack at the dockerfile / build process at some point, because it's not great

2023-11-29 01:42 UTC, MrSimmmons commented
haha yeah. There are going to probably be a few more tooling related branches when I can get around to them.
I wanted to enable ts strict mode in this one, but 1, it broke a lot. and 2, I thought this was big enough haha

Another part of me wanted to update the docker file so it wasn't using node 16, but it looks like `nodesource` doesn't allow the use of `/setup_x.x` anymore.
Generally docker is not an area I know a lot about so I elected to leave it alone lol.

Also as a side note, I'm pretty sure the live site is dead. Ive just been running it locally whenever I go to use it for something.
It wouldn't be very scaleable (if that even matters at this stage haha), but we could set it up to host on my server. Ive always wanted to set something like that up so a merge to main branch auto deploys stuff etc. Completely understand if we don't want to do that though hahahaha

2024-09-11 13:34 UTC, merged